[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
BlockArrays = "8e7c35d0-a365-5155-bbbb-fb81a777f24e"
COSMO = "1e616198-aa4e-51ec-90a2-23f7fbd31d8d"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
Convex = "f65535da-76fb-5f13-bab9-19810c17039a"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
MosekTools = "1ec41992-ff65-5c91-ac43-2df89e9693a4"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
OSQP = "ab2f91bb-94b4-55e3-9ba0-7f65df51de79"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QDLDL = "bfc457fd-c171-5ab7-bd9e-d5dbfc242d63"
RobustAndOptimalControl = "21fd56a4-db03-40ee-82ee-a87907bee541"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SCS = "c946c3f1-0d1f-5ce8-9dea-7daa1f7e2d13"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
