project:
  type: website

website:
  title: "B(E)3M35ORR – Optimal and Robust Control"
  page-footer: "Copyright 2025, Zdeněk Hurák"
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "0. Introduction"
        contents:
          - intro.qmd
          - intro_outline.qmd
          - intro_rules.qmd
          - intro_software.qmd
          - intro_references.qmd
          - text: "Similar courses"
            href: intro_similar.qmd
          - intro_projects.qmd
      - section: "1. Optimization – theory and algorithms"
        contents:
          - opt_theory_and_algo_goals.qmd
          - opt_theory_problems.qmd
          - opt_theory_reformulations.qmd
          - text: "Conditions of optimality"
            href: opt_theory_conditions.qmd
          - opt_theory_modellers.qmd
          - opt_algo_derivatives.qmd
          - text: "Numerical algorithms"
            href: opt_algo_numerical.qmd
          - opt_algo_solvers.qmd
          - opt_theory_and_algo_references.qmd
          - opt_theory_hw.qmd
          #- opt_algo_hw.qmd
      - section: "2. Discrete-time optimal control – direct approach"
        contents:
          - discr_dir_goals.qmd
          - text: "General finite-horizon nonlinear optimal control as an NLP"
            href: discr_dir_general.qmd
          - discr_dir_LQR.qmd
          - discr_dir_mpc.qmd
          - discr_dir_mpc_software.qmd
          - discr_dir_references.qmd
          - discr_dir_hw.qmd
      - section: "3. Discrete-time optimal control – indirect approach"
        contents:
          - discr_indir_goals.qmd
          - text:  "General finite-horizon nonlinear optimal control as a TP-BVP"
            href: discr_indir_general.qmd
          - discr_indir_LQR_fin_horizon.qmd
          - text: "Discrete-time LQR on an infinite horizon using the DARE"
            href: discr_indir_LQR_inf_horizon.qmd
          - discr_indir_LQR_tracking.qmd
          - discr_indir_DARE.qmd
          - discr_indir_software.qmd
          - discr_indir_references.qmd
          - discr_indir_hw.qmd
      - section: "4. Discrete-time optimal control – dynamic programming (DP)"
        contents:
          - dynamic_programming_goals.qmd
          - text: "DP and discrete-time optimal control"
            href: dynamic_programming.qmd
          - text: "Tabular outcomes of DP"
            href: dynamic_programming_tabular.qmd
          - text: "LQR via DP"
            href: dynamic_programming_LQR.qmd
          - text: "LQ tracking via DP"
            href: dynamic_programming_LQT.qmd  
          - dynamic_programming_DDP.qmd
          - dynamic_programming_references.qmd
          - dynamic_programming_hw.qmd
      - section: "5. More on MPC"
        contents:
          - discr_dir_mpc_recursive_feasibility.qmd
          - discr_dir_mpc_stability.qmd
          - discr_dir_mpc_economic.qmd
          - discr_dir_mpc_explicit.qmd
          - discr_dir_mpc_references.qmd
          - discr_dir_mpc_hw.qmd
      - section: "6. Continuous-time optimal control - indirect approach via calculus of variations"
        contents:
          - cont_indir_goals.qmd
          - cont_indir_overview.qmd
          - cont_indir_calculus_of_variations.qmd
          - text: "General finite-horizon nonlinear optimal control as a TP-BVP"
            href: cont_indir_via_calculus_of_variations.qmd
          - text: "LQR on a finite time horizon"
            href: cont_indir_LQR_fin_horizon.qmd
          - text: "LQR on an infinite time horizon using the CARE"
            href: cont_indir_LQR_inf_horizon.qmd
          #- cont_indir_CARE.qmd
          - cont_indir_notation.qmd
          - cont_indir_trajectory_stabilization.qmd
          - cont_indir_software.qmd
          - cont_indir_references.qmd
          - cont_indir_hw.qmd
      - section: "7. Continuous-time optimal control - indirect approach via Pontryagin's maximum principle"
        contents:
          - cont_indir_goals_2.qmd
          - cont_indir_Pontryagin.qmd
          - cont_indir_free_final_time.qmd
          - cont_indir_time_optimal.qmd
          - cont_indir_references_2.qmd
          - cont_indir_hw_2.qmd
      - section: "8. Numerical methods for continuous-time optimal control - both indirect and direct approaches"
        contents:
          - cont_numerical_goals.qmd
          - cont_numerical_indirect.qmd
          - cont_numerical_direct.qmd
          - cont_numerical_software.qmd
          - cont_numerical_references.qmd
          - cont_numerical_hw.qmd
      - section: "8.X. Continuous-time optimal control – dynamic programming"
        contents:
          - cont_dp_HJB.qmd
          - cont_dp_LQR.qmd
          - cont_dp_DDP.qmd
          - cont_dp_references.qmd 
          - cont_dp_hw.qmd       
      - section: "9. Some extensions: LQG, LTR, H2"
        contents:
          - ext_goals.qmd
          - text: "Guaranteed GM and PM for LQR"
            href: ext_LQR_margins.qmd
          - ext_stochastic_LQR.qmd
          - ext_LQG.qmd
          - ext_LTR.qmd
          - ext_H2.qmd
          - ext_software.qmd
          - ext_references.qmd
          - ext_hw.qmd
      - section: "10. Uncertainty modelling and robustness analysis"
        contents:
          - roban_goals.qmd
          - roban_uncertainty.qmd
          - roban_unstructured.qmd
          - roban_structured.qmd
          - roban_software.qmd
          - roban_references.qmd
          - roban_hw.qmd
      - section: "11. Robust control"
        contents:
          - rocond_goals.qmd
          - rocond_mixed_sensitivity.qmd
          - text: "H-infinity optimal control"
            href: rocond_H_infinity_control.qmd
          - rocond_software.qmd 
          - rocond_references.qmd  
          - rocond_hw.qmd
      - section: "12. Robust control II."
        contents:
          - rocond_goals.qmd
          - text: "mu synthesis"
            href: rocond_mu_synthesis.qmd
          - text: "H-infinity loop-shaping"
            href: rocond_H_infinity_loopshaping.qmd
          - rocond_software.qmd 
          - rocond_references.qmd  
          - rocond_hw.qmd 
      - section: "13. Limitations of achievable performance"
        contents:
          - limitations_goals.qmd
          - limitations_SISO.qmd
          - limitations_MIMO.qmd    
          - limitations_references.qmd 
          - limitations_hw.qmd   
      - section: "14. Model and controller order reduction"
        contents:
          - reduction_order_goals.qmd
          - reduction_order_model.qmd
          - reduction_order_controller.qmd
          - reduction_order_benchmarks.qmd
          - reduction_order_references.qmd
          - reduction_order_hw.qmd
  repo-url: https://github.com/hurak/orr
  repo-actions: [issue]       
  back-to-top-navigation: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true